/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-09 07:14:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1715225882302L));
    _jspx_dependants.put("jar:file:/C:/dev/work-space/Servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MyPage/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1715064694979L));
    _jspx_dependants.put("/views/common/head.jsp", Long.valueOf(1715227701708L));
    _jspx_dependants.put("/views/common/banner.jsp", Long.valueOf(1715236652156L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Travle Page</title>\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"/resources/css/Main.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/banner.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/footer.css\">");
      out.write("<!-- \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/banner.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/header.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/login.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- banner -->\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write(" <nav class=\"banner-container\">\r\n");
      out.write("        <a href=\"./Main.html\">\r\n");
      out.write("            <div class=\"logo\"></div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"./Detail.html\">DETAIL</a>\r\n");
      out.write("        <!-- 2depth -->\r\n");
      out.write("        <div class=\"main-menu\">\r\n");
      out.write("            <a href=\"\">REVIEW</a>\r\n");
      out.write("                <div class=\"sub-menu\">\r\n");
      out.write("                    <li><a href=\"./Review-asia.html\">ASIA</a></li>\r\n");
      out.write("                    <li><a href=\"./Review-europe.html\">EUROPE</a></li>\r\n");
      out.write("                    <li><a href=\"./Review-ko.html\">KO</a></li>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("            <!-- 2depth -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"signin\">\r\n");
      out.write("            <a href=\"/form/loginForm.do\">로그인</a>\r\n");
      out.write("            <a href=\"/form/registerForm.do\">회원가입</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"login-container\">\r\n");
      out.write("        <div class=\"login-main\">\r\n");
      out.write("            <h2>로그인</h2>\r\n");
      out.write("            <p>해당 페이지를 이용하시려면 본인 확인을 위해 다시 한 번 로그인해 주시기 바랍니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"login-links\">\r\n");
      out.write("            <a class=\"login-email\" href=\"./login.html\">이메일</a>\r\n");
      out.write("            <a class=\"login-phone\" href=\"./login-phone.html\">휴대전화</a>\r\n");
      out.write("            <br>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"/member/login.do\" method=\"POST\">\r\n");
      out.write("            <div class=\"login-box\">\r\n");
      out.write("                <label for=\"email\">이메일</label>\r\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"useremail\" required placeholder=\"이메일\"><br>\r\n");
      out.write("                <label for=\"password\">비밀번호</label>\r\n");
      out.write("                <input type=\"password\" id=\"password\" name=\"userpassword\" required placeholder=\"비밀번호\"><br>\r\n");
      out.write("\r\n");
      out.write("                <button class=\"login-button\" onclick=\"login()\">로그인</button>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"./register.html\">\r\n");
      out.write("                    <span class=\"register\">회원가입</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 로그인, 회원가입 footer -->\r\n");
      out.write("            <div>\r\n");
      out.write("                <span>혹은 아래 계정을 이용해 로그인</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <button class=\"google-but but\" type=\"button\">\r\n");
      out.write("                    <img src=\"https://cdn6.agoda.net/images/universal-login/google-logo-v2.svg\" alt=\"구글\">\r\n");
      out.write("                    <span>구글</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"facebook-but but\" type=\"button\">\r\n");
      out.write("                    <img src=\"https://cdn6.agoda.net/images/universal-login/facebook-logo.svg\" alt=\"페이스북\">\r\n");
      out.write("                    <span>페이스북</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"apple-but but\" type=\"button\">\r\n");
      out.write("                    <img src=\"https://cdn6.agoda.net/images/universal-login/apple-logo.svg\" alt=\"애플\">\r\n");
      out.write("                    <span>애플</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- </body> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- footer -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write(" <footer>\r\n");
      out.write("        <table class=\"table\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <th>도움말-문의</th>\r\n");
      out.write("                <th>회사명</th>\r\n");
      out.write("                <th>여행지</th>\r\n");
      out.write("                <th>파트너</th>\r\n");
      out.write("                <th>모바일 GREEN</th>\r\n");
      out.write("            </thead>\r\n");
      out.write("\r\n");
      out.write("            <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>도움말센터</td>\r\n");
      out.write("                    <td>회사 소개</td>\r\n");
      out.write("                    <td>국가별</td>\r\n");
      out.write("                    <td>YCS 파트너 포털</td>\r\n");
      out.write("                    <td>IOS</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>자주 묻는 질문 FAQ</td>\r\n");
      out.write("                    <td>채용 정보</td>\r\n");
      out.write("                    <td>도시별</td>\r\n");
      out.write("                    <td>Partner Hub</td>\r\n");
      out.write("                    <td>Android</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>개인정보 처리방침</td>\r\n");
      out.write("                    <td>프레스센터 / 보도자료</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td>광고문의</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>쿠키 정책</td>\r\n");
      out.write("                    <td>블로그</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td>제휴 파트너</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>이용 약관</td>\r\n");
      out.write("                    <td>포인트맥스</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td>커넥티비티 파트너</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>쿠키 설정 관리</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Digital Service Act(EU)</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"spon\">\r\n");
      out.write("            <a href=\"https://flyairseoul.com/CW/ko/main.do\" target=\"_blank\"><img src=\"/resources/img/airplane.svg\"\r\n");
      out.write("                    alt=\"airplane\"></a>\r\n");
      out.write("            <a href=\"https://www.youtube.com/\" target=\"_blank\"><img src=\"/resources/img/caret-right-square-fill.svg\"\r\n");
      out.write("                    alt=\"youtube\"></a>\r\n");
      out.write("            <a href=\"https://www.weather.go.kr/w/index.doa\" target=\"_blank\"><img src=\"/resources/img/cloud-rain-heavy-fill.svg\"\r\n");
      out.write("                    alt=\"weather\"></a>\r\n");
      out.write("            <a href=\"https://www.instagram.com/\" target=\"_blank\"><img src=\"/resources/img/instagram.svg\" alt=\"instagram\"></a>\r\n");
      out.write("            <a href=\"https://www.threads.net/login\" target=\"_blank\"><img src=\"/resources/img/threads-fill.svg\" alt=\"threads\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- <script>\r\n");
      out.write("    function login() {\r\n");
      out.write("        const id = \"user@naver.com\";\r\n");
      out.write("        const pwd = \"qwer1234\";\r\n");
      out.write("\r\n");
      out.write("        const inputId = document.getElementById('email').value;\r\n");
      out.write("        const inputPwd = document.getElementById('password').value;\r\n");
      out.write("\r\n");
      out.write("        if (!inputId || !inputPwd) {\r\n");
      out.write("            alert(\"아이디 또는 비밀번호를 입력해주세요\");\r\n");
      out.write("        } else if (inputId !== id || inputPwd !== pwd) {\r\n");
      out.write("            alert(\"아이디 또는 비밀번호가 틀렸습니다.\");\r\n");
      out.write("        } else {\r\n");
      out.write("            alert(\"로그인 되었습니다.\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script> -->\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
