/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-09 06:37:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1715225276352L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1715225882302L));
    _jspx_dependants.put("jar:file:/C:/dev/work-space/Servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MyPage/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/views/common/Main.jsp", Long.valueOf(1715225738611L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1715064694979L));
    _jspx_dependants.put("/views/common/head.jsp", Long.valueOf(1715227701708L));
    _jspx_dependants.put("/views/common/banner.jsp", Long.valueOf(1715236652156L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/Main.css\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Travle Page</title>\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"/resources/css/Main.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/banner.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/footer.css\">");
      out.write("\r\n");
      out.write("  <!--   <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Travle Page</title> -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"./Main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./banner.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./footer.css\">  -->\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- banner -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write(" <nav class=\"banner-container\">\r\n");
      out.write("        <a href=\"./Main.html\">\r\n");
      out.write("            <div class=\"logo\"></div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"./Detail.html\">DETAIL</a>\r\n");
      out.write("        <!-- 2depth -->\r\n");
      out.write("        <div class=\"main-menu\">\r\n");
      out.write("            <a href=\"\">REVIEW</a>\r\n");
      out.write("                <div class=\"sub-menu\">\r\n");
      out.write("                    <li><a href=\"./Review-asia.html\">ASIA</a></li>\r\n");
      out.write("                    <li><a href=\"./Review-europe.html\">EUROPE</a></li>\r\n");
      out.write("                    <li><a href=\"./Review-ko.html\">KO</a></li>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("            <!-- 2depth -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"signin\">\r\n");
      out.write("            <a href=\"/form/loginForm.do\">로그인</a>\r\n");
      out.write("            <a href=\"/form/registerForm.do\">회원가입</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>");
      out.write("\r\n");
      out.write("   <!--  <nav class=\"banner-container\">\r\n");
      out.write("        <a href=\"./Main.html\">\r\n");
      out.write("            <div class=\"logo\"></div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"./Detail.html\">DETAIL</a>\r\n");
      out.write("        2depth\r\n");
      out.write("        <div class=\"main-menu\">\r\n");
      out.write("            <a href=\"\">REVIEW</a>\r\n");
      out.write("                <div class=\"sub-menu\">\r\n");
      out.write("                    <li><a href=\"./Review-asia.html\">ASIA</a></li>\r\n");
      out.write("                    <li><a href=\"./Review-europe.html\">EUROPE</a></li>\r\n");
      out.write("                    <li><a href=\"./Review-ko.html\">KO</a></li>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("            2depth\r\n");
      out.write("\r\n");
      out.write("        <div class=\"signin\">\r\n");
      out.write("            <a href=\"./login.html\">로그인</a>\r\n");
      out.write("            <a href=\"./register.html\">회원가입</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- header -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<header>\r\n");
      out.write("        <!-- background image -->\r\n");
      out.write("        <div class=\"header\">GREEN과 함께 행복을 찾으세요!</div>\r\n");
      out.write("\r\n");
      out.write("        <!-- select box -->\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"main-box\">\r\n");
      out.write("                <input type=\"text\" class=\"where\" placeholder=\"🇰🇷 어디로 떠나시나요?\">\r\n");
      out.write("                <input type=\"number\" class=\"people\" placeholder=\"🎅🏻 인원을 설정해주세요.\">\r\n");
      out.write("                <label for=\"start\" class=\"start-label\"> 🛫 출발일을 설정해주세요 </label>\r\n");
      out.write("                <input type=\"date\" class=\"start\" id=\"start\">\r\n");
      out.write("                <label for=\"end\" class=\"end-label\"> 🛬 도착일을 설정해주세요 </label>\r\n");
      out.write("                <input type=\"date\" class=\"end\" id=\"end\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\" class=\"btn\">검색하기</button>\r\n");
      out.write("        </section>\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("    <!-- <header>\r\n");
      out.write("        background image\r\n");
      out.write("        <div class=\"header\">GREEN과 함께 행복을 찾으세요!</div>\r\n");
      out.write("\r\n");
      out.write("        select box\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"main-box\">\r\n");
      out.write("                <input type=\"text\" class=\"where\" placeholder=\"🇰🇷 어디로 떠나시나요?\">\r\n");
      out.write("                <input type=\"number\" class=\"people\" placeholder=\"🎅🏻 인원을 설정해주세요.\">\r\n");
      out.write("                <label for=\"start\" class=\"start-label\"> 🛫 출발일을 설정해주세요 </label>\r\n");
      out.write("                <input type=\"date\" class=\"start\" id=\"start\">\r\n");
      out.write("                <label for=\"end\" class=\"end-label\"> 🛬 도착일을 설정해주세요 </label>\r\n");
      out.write("                <input type=\"date\" class=\"end\" id=\"end\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\" class=\"btn\">검색하기</button>\r\n");
      out.write("        </section>\r\n");
      out.write("    </header> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Main -->\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write(" <main>\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("            <div class=\"part1\">인기 여행지</div>\r\n");
      out.write("            <img src=\"/resources/img/busan.png\" alt=\"인기 여행지\">\r\n");
      out.write("            <img src=\"/resources/img/daegu.png\" alt=\"인기 여행지\">\r\n");
      out.write("            <img src=\"/resources/img/china.png\" alt=\"인기 여행지\">\r\n");
      out.write("            <img src=\"/resources/img/europe.png\" alt=\"인기 여행지\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"part2\">여행객 리뷰</div>\r\n");
      out.write("            <img src=\"/resources/img/review.png\" alt=\"리뷰\">\r\n");
      out.write("            <img src=\"/resources/img/review2.png\" alt=\"리뷰\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>");
      out.write("\r\n");
      out.write("    <!-- <main>\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("            <div class=\"part1\">인기 여행지</div>\r\n");
      out.write("            <img src=\"./img/busan.png\" alt=\"인기 여행지\">\r\n");
      out.write("            <img src=\"./img/daegu.png\" alt=\"인기 여행지\">\r\n");
      out.write("            <img src=\"./img/china.png\" alt=\"인기 여행지\">\r\n");
      out.write("            <img src=\"./img/europe.png\" alt=\"인기 여행지\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"part2\">여행객 리뷰</div>\r\n");
      out.write("            <img src=\"./img/review.png\" alt=\"리뷰\">\r\n");
      out.write("            <img src=\"./img/review2.png\" alt=\"리뷰\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </main> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- footer -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write(" <footer>\r\n");
      out.write("        <table class=\"table\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <th>도움말-문의</th>\r\n");
      out.write("                <th>회사명</th>\r\n");
      out.write("                <th>여행지</th>\r\n");
      out.write("                <th>파트너</th>\r\n");
      out.write("                <th>모바일 GREEN</th>\r\n");
      out.write("            </thead>\r\n");
      out.write("\r\n");
      out.write("            <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>도움말센터</td>\r\n");
      out.write("                    <td>회사 소개</td>\r\n");
      out.write("                    <td>국가별</td>\r\n");
      out.write("                    <td>YCS 파트너 포털</td>\r\n");
      out.write("                    <td>IOS</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>자주 묻는 질문 FAQ</td>\r\n");
      out.write("                    <td>채용 정보</td>\r\n");
      out.write("                    <td>도시별</td>\r\n");
      out.write("                    <td>Partner Hub</td>\r\n");
      out.write("                    <td>Android</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>개인정보 처리방침</td>\r\n");
      out.write("                    <td>프레스센터 / 보도자료</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td>광고문의</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>쿠키 정책</td>\r\n");
      out.write("                    <td>블로그</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td>제휴 파트너</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>이용 약관</td>\r\n");
      out.write("                    <td>포인트맥스</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td>커넥티비티 파트너</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>쿠키 설정 관리</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Digital Service Act(EU)</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"spon\">\r\n");
      out.write("            <a href=\"https://flyairseoul.com/CW/ko/main.do\" target=\"_blank\"><img src=\"/resources/img/airplane.svg\"\r\n");
      out.write("                    alt=\"airplane\"></a>\r\n");
      out.write("            <a href=\"https://www.youtube.com/\" target=\"_blank\"><img src=\"/resources/img/caret-right-square-fill.svg\"\r\n");
      out.write("                    alt=\"youtube\"></a>\r\n");
      out.write("            <a href=\"https://www.weather.go.kr/w/index.doa\" target=\"_blank\"><img src=\"/resources/img/cloud-rain-heavy-fill.svg\"\r\n");
      out.write("                    alt=\"weather\"></a>\r\n");
      out.write("            <a href=\"https://www.instagram.com/\" target=\"_blank\"><img src=\"/resources/img/instagram.svg\" alt=\"instagram\"></a>\r\n");
      out.write("            <a href=\"https://www.threads.net/login\" target=\"_blank\"><img src=\"/resources/img/threads-fill.svg\" alt=\"threads\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("    <!-- <footer>\r\n");
      out.write("        <table class=\"table\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <th>도움말-문의</th>\r\n");
      out.write("                <th>회사명</th>\r\n");
      out.write("                <th>여행지</th>\r\n");
      out.write("                <th>파트너</th>\r\n");
      out.write("                <th>모바일 GREEN</th>\r\n");
      out.write("            </thead>\r\n");
      out.write("\r\n");
      out.write("            <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>도움말센터</td>\r\n");
      out.write("                    <td>회사 소개</td>\r\n");
      out.write("                    <td>국가별</td>\r\n");
      out.write("                    <td>YCS 파트너 포털</td>\r\n");
      out.write("                    <td>IOS</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>자주 묻는 질문 FAQ</td>\r\n");
      out.write("                    <td>채용 정보</td>\r\n");
      out.write("                    <td>도시별</td>\r\n");
      out.write("                    <td>Partner Hub</td>\r\n");
      out.write("                    <td>Android</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>개인정보 처리방침</td>\r\n");
      out.write("                    <td>프레스센터 / 보도자료</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td>광고문의</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>쿠키 정책</td>\r\n");
      out.write("                    <td>블로그</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td>제휴 파트너</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>이용 약관</td>\r\n");
      out.write("                    <td>포인트맥스</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td>커넥티비티 파트너</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>쿠키 설정 관리</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Digital Service Act(EU)</td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"spon\">\r\n");
      out.write("            <a href=\"https://flyairseoul.com/CW/ko/main.do\" target=\"_blank\"><img src=\"./img/airplane.svg\"\r\n");
      out.write("                    alt=\"airplane\"></a>\r\n");
      out.write("            <a href=\"https://www.youtube.com/\" target=\"_blank\"><img src=\"./img/caret-right-square-fill.svg\"\r\n");
      out.write("                    alt=\"youtube\"></a>\r\n");
      out.write("            <a href=\"https://www.weather.go.kr/w/index.doa\" target=\"_blank\"><img src=\"./img/cloud-rain-heavy-fill.svg\"\r\n");
      out.write("                    alt=\"weather\"></a>\r\n");
      out.write("            <a href=\"https://www.instagram.com/\" target=\"_blank\"><img src=\"./img/instagram.svg\" alt=\"instagram\"></a>\r\n");
      out.write("            <a href=\"https://www.threads.net/login\" target=\"_blank\"><img src=\"./img/threads-fill.svg\" alt=\"threads\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer> -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
